# Generated by Django 4.0.3 on 2022-04-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(default='', max_length=9, unique=b'I01\n')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telfono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroSerie', models.IntegerField(default='', unique=b'I01\n')),
                ('modelo', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=30)),
                ('tipoEquipo', models.CharField(max_length=30)),
                ('proveedorNombre', models.CharField(max_length=30)),
                ('proveedorTelefono', models.IntegerField()),
                ('planta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroReferencia', models.IntegerField(unique=b'I01\n')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('nivelUrgencia', models.CharField(max_length=5)),
                ('tipoTicket', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('comentarios', models.CharField(max_length=500)),
                ('DNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProyectoIW_Grupo3.empleado')),
                ('numeroSerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProyectoIW_Grupo3.equipo')),
            ],
        ),
    ]
