# Generated by Django 4.0.3 on 2022-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectoIW_Grupo3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='id',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='DNI',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numeroSerie',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
