# Generated by Django 4.0.3 on 2022-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectoIW_Grupo3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='DNI',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='numeroSerie',
            new_name='equipo',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='DNI',
            field=models.CharField(max_length=9, unique=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numeroSerie',
            field=models.IntegerField(unique=b'I01\n'),
        ),
    ]