# Generated by Django 4.0.3 on 2022-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectoIW_Grupo3', '0004_equipo_fechaadquisicion_equipo_fechapuestamarcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nivelUrgencia',
            field=models.CharField(choices=[('ALTO', 'alto'), ('MEDIO', 'medio'), ('BAJO', 'bajo')], max_length=5),
        ),
    ]
