# Generated by Django 4.0.3 on 2022-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectoIW_Grupo3', '0007_alter_ticket_nivelurgencia_alter_ticket_tipoticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nivelUrgencia',
            field=models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], default='MEDIO', max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipoTicket',
            field=models.CharField(choices=[('AVERIA', 'Avería'), ('MEJORA', 'Mejora'), ('MANTENIMIENTO', 'Mantenimiento')], default='MANTENIMIENTO', max_length=20),
        ),
    ]
